### ISSUE TITLE
Additional data

### ISSUE THREAD

**Issue by RandyHarr** [YFullTeam/YTree#1]
Any chance to add additional summary data like the number of samples per node and maybe even countries identified per node?  This is provided with the FTDNA public tree (download) and some are asking for comparisons.  Personally, I am fine with what is here otherwise and appreciate the support. Ditto request for the mtree.

**Comment by YFullTeam** [comment]
At this point in time, we do not plan to add additional data to YTree (JSON).
FTDNA does not officially release its tree for download.
